# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-02 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('male', models.BooleanField(default=False)),
                ('female', models.BooleanField(default=False)),
                ('age15_20', models.BooleanField(default=False)),
                ('age21_30', models.BooleanField(default=False)),
                ('age31_40', models.BooleanField(default=False)),
                ('age41_50', models.BooleanField(default=False)),
                ('age51', models.BooleanField(default=False)),
                ('qatar_resident', models.BooleanField(default=True)),
                ('source', models.CharField(max_length=200)),
                ('children', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('male', models.BooleanField(default=False)),
                ('female', models.BooleanField(default=False)),
                ('age1520', models.BooleanField(default=False)),
                ('age2130', models.BooleanField(default=False)),
                ('age3140', models.BooleanField(default=False)),
                ('age4150', models.BooleanField(default=False)),
                ('age51', models.BooleanField(default=False)),
                ('qatar_resident', models.BooleanField(default=True)),
                ('source', models.CharField(max_length=200)),
                ('children', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('qatar_resident', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('children', models.CharField(max_length=200)),
            ],
        ),
    ]
