# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-02 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='female',
            new_name='woman',
        ),
    ]
