# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-02 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161102_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='male',
            new_name='man',
        ),
    ]
