# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161102_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='api')),
                ('mimeType', models.CharField(max_length=20)),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Poster')),
            ],
        ),
    ]
