# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='api/img'),
        ),
    ]
